### ISSUE TITLE
插件如何打开并实现无障碍

### ISSUE THREAD

**Issue by zxfcfj** [GitLqr/RePluginX#3]
#### 复现问题步骤 Steps to reproduce the problem
1. 
2. 

#### 其它重要信息 Other important information

replugin-host-lib/gradle Version:
rePlugin-plugin-lib/gradle Version:

Android API Version：
Android 手机型号&ROM(Phone model & ROM):

**Comment by GitLqr** [comment]
这部分 RePlugin X 的处理与 RePlugin 是一样的, 请到官方 RePlugin 仓库查下issue是否有相关问题

**Comment by zxfcfj** [comment]
官方也没有有关这方面的资料，找了好多，不知道要如如何实现

**Comment by zxfcfj** [comment]
按照你的办法去查了源码，解决了，但是androidX 不能用出现如下错误
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/AppCompatActivity
import android.os.Bundle;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.preference.PreferenceFragmentCompat;

import com.qihoo360.replugin.sample.aiplugin.R;

/**
 * @author gentile
 */
public class SettingsActivity extends AppCompatActivity {
}

**Comment by zxfcfj** [comment]
继承 public class SettingsActivity extends PluginAppCompatActivityAndroidX {}也不行
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qihoo360.replugin.sample.aiplugin, PID: 20998
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qihoo360/replugin/sample/aiplugin/setting/SettingsActivity;
        at com.qihoo360.replugin.sample.aiplugin.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:204)
